CREATE TABLE IF NOT EXISTS "merchant"
(
    "id"                    bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id"               bigint       NOT NULL DEFAULT 0,
    "name"                  varchar(64)  NOT NULL DEFAULT '',
    "short_name"            varchar(64)  NOT NULL DEFAULT '',
    "logo"                  varchar(255) NOT NULL DEFAULT '',
    "remark"                varchar(255) NOT NULL DEFAULT '',
    "status"                tinyint      NOT NULL DEFAULT 0,
    "merchant_type"         tinyint      NOT NULL DEFAULT 1,
    "huifu_id"              varchar(18)  NOT NULL DEFAULT '',
    "ext_mer_id"            varchar(64)  NOT NULL DEFAULT '',
    "contact_name"          varchar(128) NOT NULL DEFAULT '',
    "contact_mobile"        varchar(11)  NOT NULL DEFAULT '',
    "contact_email"         varchar(32)  NOT NULL DEFAULT '',
    "settle_card_no_masked" varchar(32)  NOT NULL DEFAULT '',
    "submit_time"           datetime,
    "effect_time"           datetime,
    "creator"               varchar(64)  DEFAULT '',
    "create_time"           datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"               varchar(64)  DEFAULT '',
    "update_time"           datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"               bit          NOT NULL DEFAULT FALSE,
    "tenant_id"             bigint       NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "merchant_apply"
(
    "id"              bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "merchant_id"     bigint       NOT NULL DEFAULT 0,
    "req_seq_id"      varchar(32)  NOT NULL,
    "req_date"        varchar(8)   NOT NULL,
    "apply_no"        varchar(18)  NOT NULL DEFAULT '',
    "status"          tinyint      NOT NULL DEFAULT 4,
    "audit_status"    varchar(1)   NOT NULL DEFAULT '',
    "audit_desc"      varchar(512) NOT NULL DEFAULT '',
    "huifu_id"        varchar(18)  NOT NULL DEFAULT '',
    "token_no"        varchar(20)  NOT NULL DEFAULT '',
    "submit_time"     datetime,
    "audit_time"      datetime,
    "raw_notify_json" text,
    "creator"         varchar(64)  DEFAULT '',
    "create_time"     datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"         varchar(64)  DEFAULT '',
    "update_time"     datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"         bit          NOT NULL DEFAULT FALSE,
    "tenant_id"       bigint       NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "merchant_image"
(
    "id"            bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "merchant_id"   bigint       NOT NULL DEFAULT 0,
    "biz_type"      varchar(8)   NOT NULL,
    "infra_file_id" bigint       NOT NULL DEFAULT 0,
    "huifu_file_id" varchar(128) NOT NULL DEFAULT '',
    "creator"       varchar(64)  DEFAULT '',
    "create_time"   datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"       varchar(64)  DEFAULT '',
    "update_time"   datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"       bit          NOT NULL DEFAULT FALSE,
    "tenant_id"     bigint       NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
);
